default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: muh_db/development

test:
  <<: *default
  database: muh_db/test

production:
  <<: *default
  database: muh_db/production
